version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: credito-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: credito_db
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
